name: publish texlive images
on:
  workflow_dispatch:
  push:
    paths:
      - 'texlive/2019/**'
      - 'texlive/2019-extra/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      PREFIX: ghcr.io/sarisia/
      VARIANT: texlive
      VERSION: 2019
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - name: login to ghcr
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login -u sarisia --password-stdin ${{ env.REGISTRY }}

      - name: build latest
        run: docker build -t ${{ env.PREFIX }}${{ env.VARIANT }}:${{ env.VERSION }} ./${{ env.VARIANT }}/${{ env.VERSION }}
      - name: push ${{ env.VARIANT }}:${{ env.VERSION }}
        if: ${{ github.ref }} == "refs/heads/master"
        run: docker push ${{ env.PREFIX }}${{ env.VARIANT }}:${{ env.VERSION }}

      - name: build extra
        run: docker build -t ${{ env.PREFIX }}${{ env.VARIANT }}:${{ env.VERSION }}-extra ./${{ env.VARIANT }}/${{ env.VERSION }}-extra
      - name: push ${{ env.VARIANT }}:${{ env.VERSION }}-extra
        if: ${{ github.ref }} == "refs/heads/master"
        run: docker push ${{ env.PREFIX }}${{ env.VARIANT }}:${{ env.VERSION }}-extra

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
